DjangoHostingManagement/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from DjangoHostingManagement import settings
from core import views

urlpatterns = [
    path('dhmadmin/', admin.site.urls),
    path('core/', include("core.urls")),
    path('sysinfo/', include("sysinfo.urls")),
    path('btm/', include("btm.urls")),
    path('wam/', include("webappmanager.urls")),
    path('', views.index, name='home'),
]

admin.site.site_header = "DHM"
admin.site.site_title = "Django Hosting Manager"
admin.site.index_title = "Welcome to the Django Hosting Manager"

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

btm/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from btm import views

__author__ = 'ozgur'
__creation_date__ = '23.04.2019' '23:01'
urlpatterns = [
    path('ati/', views.ajax_thread_info, name='ati'),
    path('getthreadinfo/<str:tid>', views.getthreadinfo, name='getthreadinfo'),
    path('testthreadinfo/', views.testthreadinfo, name='testthreadinfo'),
]

webappmanager/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from webappmanager import views

__author__ = 'ozgur'
__creation_date__ = '01.07.2019' '13:53'

urlpatterns = [
    path('walist/', views.getwalist, name='getwalist'),
    path('addwa/', views.addwa, name='addwa'),
    path('rmwa/<int:appid>', views.rmwa, name='rmwa'),
]

webappmanager/models.py
# -*- coding: utf-8 -*-
from django.db import models

__author__ = 'ozgur'
__creation_date__ = '01.07.2019' '13:53'


class Webapp(models.Model):
    appname = models.CharField(max_length=50, verbose_name="Application Name", unique=True)
    url = models.URLField(max_length=250, verbose_name="URL")
    giturl = models.CharField(max_length=250, verbose_name="Git URL")
    dbname = models.CharField(max_length=50, verbose_name="DB Name")
    dbuser = models.CharField(max_length=50, verbose_name="DB User")
    dbpass = models.CharField(max_length=50, verbose_name="DB Pass")
    settingsfoldername = models.CharField(max_length=50, verbose_name="Settings Folder Path")
    staticfolder = models.CharField(max_length=250, default="static/",verbose_name="Static Folder Path")
    staticurl = models.CharField(max_length=50, default="/static/",verbose_name="Static URL")
    mediafolder = models.CharField(max_length=250, default="media/", verbose_name="Media Folder Path")
    mediaurl = models.CharField(max_length=50, default="/media/",verbose_name="Media URL")
    isinstalledsuccess = models.BooleanField(default=False, blank=True,
                                             verbose_name="Is Installed Succesfully")

    localsettings=models.TextField(null=True, blank=True, verbose_name="local_settings.py content")

    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Created At")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Updated At")

    class Meta:
        verbose_name = 'Webapp'
        verbose_name_plural = 'Webapps'
        ordering = ('-id',)

    def __str__(self):
        return str(self.appname)

    def get_short_name(self):
        return str(self.appname)

webappmanager/forms.py
# -*- coding: utf-8 -*-
from django import forms

from webappmanager.models import Webapp

__author__ = 'ozgur'
__creation_date__ = '01.07.2019' '14:14'


class WebAppForm(forms.ModelForm):
    class Meta:
        model = Webapp
        exclude = ["isinstalledsuccess"]
        widgets = {
            'appname': forms.TextInput(attrs={"class": "form-control", "placeholder": "Unique application name"}),
            'url': forms.URLInput(attrs={"class": "form-control", "placeholder": "Global URL of the application"}),
            'giturl': forms.TextInput(attrs={"class": "form-control", "placeholder": "Source code repo of the application"}),
            'dbname': forms.TextInput(attrs={"class": "form-control", "placeholder": "db name in settings.py"}),
            'dbuser': forms.TextInput(attrs={"class": "form-control", "placeholder": "db user in settings.py"}),
            'dbpass': forms.PasswordInput(attrs={"class": "form-control", "placeholder": "db password in settings.py"}),
            'settingsfoldername': forms.TextInput(
                attrs={"class": "form-control", "placeholder": "settings.py's folder name relative to project folder"}),
            'staticfolder': forms.TextInput(attrs={"class": "form-control", "placeholder": "static folder name relative to project folder e.g: static/"}),
            'staticurl': forms.TextInput(attrs={"class": "form-control", "placeholder": "static url relative to project url e.g: /static/"}),
            'mediafolder': forms.TextInput(attrs={"class": "form-control", "placeholder": "media folder name relative to project folder e.g: media/"}),
            'mediaurl': forms.TextInput(attrs={"class": "form-control", "placeholder": "media url relative to project url e.g: /media/"}),
            'localsettings': forms.Textarea(attrs={"class": "form-control", "placeholder": "optional: local_settings.py content"}),
        }

webappmanager/views.py
# -*- coding: utf-8 -*-
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse

from webappmanager.backendtasks import AddWebAppThread, DeleteWebAppThread
from webappmanager.forms import WebAppForm
from webappmanager.models import Webapp

__author__ = 'ozgur'
__creation_date__ = '01.07.2019' '13:53'


@login_required
def getwalist(request):
    return render(request, "wam/wam.html", {"webapps":Webapp.objects.all()})


@login_required
def addwa(request):
    if request.method == 'POST':
        waform = WebAppForm( request.POST)
        if waform.is_valid():
            webapp = waform.save()
            suuser=request.POST.get("ext_suname", None)
            sumail=request.POST.get("ext_sumail", None)
            supass=request.POST.get("ext_supass", None)

            addwathread = AddWebAppThread(webapp,suuser=suuser,sumail=sumail,supass=supass)
            addwathread.start()

            retdict = {
                "tid": addwathread.get_thread_id()
            }
        else:
            retdict = {
                "waform": waform
            }

    else:
        retdict = {
            "waform": WebAppForm()

        }
    return render(request, "wam/addwa.html", retdict)


@login_required
def rmwa(request,appid):
    webapp =Webapp.objects.get(id=appid)
    deletewathread = DeleteWebAppThread(webapp)
    deletewathread.start()
    tid=deletewathread.get_thread_id()
    return redirect(reverse("getthreadinfo", args=[tid]))

webappmanager/templates/wam/addwa.html
{% extends "core/container.html" %}

{% block CONTENT %}
    <div class="row">
        <section class="col-lg-12">
            <div class="box box-primary">
                <div class="box-body">
                    <a href="{% url 'getwalist' %}" type="button" class="btn bg-green btn-flat margin">
                        <i class="fa fa-fw fa-backward"></i> Back To The Future</a>
                </div>
                <!-- /.box-body -->
            </div>
        </section>
    </div>

    <div class="row">
        <section class="col-lg-12">
            <div class="box box-primary">
                <div class="box-body">
                    {% if waform %}
                        <form action="{% url 'addwa' %}" method="post">
                            {% csrf_token %}
                            <table class="table table-responsive">
                                {{ waform.as_table }}
                                <tr>
                                    <td colspan="2" class="text-center text-orange">
                                        Below values are for one time execution and will not be stored !
                                    </td>
                                </tr>
                                <tr>
                                    <th><label for="ext_suname">Superuser Name:</label></th>
                                    <td>
                                        <input type="text" name="ext_suname" value="" class="form-control" placeholder="superuser name" maxlength="50" required="" id="ext_suname">
                                    </td>
                                </tr>
                                <tr>
                                    <th><label for="ext_sumail">Superuser Mail:</label></th>
                                    <td>
                                        <input type="email" name="ext_sumail" value="" class="form-control" placeholder="superuser e-mail" maxlength="50" required="" id="ext_sumail">
                                    </td>
                                </tr>
                                <tr>
                                    <th><label for="ext_supass">Superuser Password:</label></th>
                                    <td>
                                        <input type="password" name="ext_supass" value="" class="form-control" placeholder="superuser pasword" maxlength="50" required="" id="ext_supass">
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="2">
                                        <input type="submit" class="btn btn-block btn-primary btn-flat" value="Install">
                                    </td>
                                    <td></td>
                                </tr>
                            </table>
                        </form>
                    {% endif %}
                    {% if tid %}
                        {% load btm_filters %}
                        {{ tid|thread_info }}
                    {% endif %}
                </div>
                <!-- /.box-body -->
            </div>
        </section>
    </div>
{% endblock %}
{% block EXTRA_CSS %}{% endblock %}
{% block EXTRA_SCRIPT %}
    <script type="text/javascript">
        $(document).ready(function(){
            dhm.enabletab("#id_localsettings");
        });
    </script>
{% endblock %}

webappmanager/templates/wam/wam.html
{% extends "core/container.html" %}

{% block CONTENT %}
    <div class="row">
        <section class="col-lg-12">
            <div class="box box-primary">
                <div class="box-body">
                    <a href="{% url 'addwa' %}" type="button" class="btn bg-green btn-flat margin">New WebApp</a>
                    <a href="#" type="button" class="btn bg-yellow btn-flat margin">Logs</a>
                </div>
                <!-- /.box-body -->
            </div>
        </section>
    </div>
    <div class="row">
        <section class="col-lg-12">
            <div class="box box-success">
                <div class="box-body">
                    <div class="box-group" id="accordion">

                        {% for webapp in webapps %}
                            <div class="panel box box-primary">
                                <div class="box-header with-border">
                                    <h4 class="box-title">

                                        <a data-toggle="collapse" data-parent="#accordion" href="#wadetail{{ webapp.id }}">
                                            {{ webapp.appname }}
                                        </a>
                                    </h4>

                                    <div class="pull-right">
                                        <span class="text-fuchsia" title="Size On Disk"> 120 Mb </span>, &nbsp;
                                        <span class="text-maroon" title="Ram Usage"> 60 Mb </span>, &nbsp;
                                        {% if webapp.isinstalledsuccess %}
                                            <i class="fa fa-fw  fa-cloud-download text-success" title="Succesfully Installed"></i>
                                        {% else %}
                                            <i class="fa fa-fw  fa-cloud-download text-danger" title="Failed On Install"></i>
                                        {% endif %}

                                        <i class="fa fa-fw fa-link text-success" title="running"></i>
                                    </div>
                                </div>

                                <div id="wadetail{{ webapp.id }}" class="panel-collapse collapse">
                                    <div class="box-body">
                                        <table class="table table-responsive">
                                            <tr>
                                                <td class="text-bold text-black"> Application Name:</td>
                                                <td class="text-green">{{ webapp.appname }}</td>
                                                <td class="text-bold text-black"> Settings Folder:</td>
                                                <td class="text-green">{{ webapp.settingsfoldername }}</td>
                                            </tr>
                                            <tr>
                                                <td class="text-bold text-black">URL :</td>
                                                <td class="text-blue">
                                                    <a href="{{ webapp.url }}" target="_blank">{{ webapp.url }}</a>
                                                </td>
                                                <td class="text-bold text-black"> Git Url :</td>
                                                <td class="text-blue">
                                                    <a href="{{ webapp.giturl }}" target="_blank">{{ webapp.giturl }}</a>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td class="text-bold text-black">DB Name :</td>
                                                <td class="text-green">{{ webapp.dbname }}</td>
                                                <td class="text-bold text-black">DB User :</td>
                                                <td class="text-green">{{ webapp.dbuser }}</td>
                                            </tr>
                                            <tr>
                                                <td class="text-bold text-black">Static Folder :</td>
                                                <td class="text-green">{{ webapp.staticfolder }}</td>
                                                <td class="text-bold text-black">Static Url :</td>
                                                <td class="text-green">{{ webapp.staticurl }}</td>
                                            </tr>
                                            <tr>
                                                <td class="text-bold text-black">Media folder :</td>
                                                <td class="text-green">{{ webapp.mediafolder }}</td>
                                                <td class="text-bold text-black">Media Url :</td>
                                                <td class="text-green">{{ webapp.mediaurl }}</td>
                                            </tr>
                                            <tr>
                                                <td class="text-bold text-black">Created At :</td>
                                                <td class="text-green">{{ webapp.created_at }}</td>
                                                <td class="text-bold text-black">Updated At :</td>
                                                <td class="text-green">{{ webapp.updated_at }}</td>
                                            </tr>
                                        </table>
                                        <hr>
                                        <div class="btn-group pull-right">
                                            <button type="button" class="btn btn-success btn-flat">
                                                Run
                                            </button>
                                            <button type="button" class="btn btn-warning btn-flat">
                                                Stop
                                            </button>
                                            <button type="button" class="btn btn-primary btn-flat">
                                                Backup
                                            </button>
                                            <button type="button" class="btn btn-info btn-flat">
                                                Update
                                            </button>
                                            <button type="button" class="btn btn-danger btn-flat" onclick="deleteWebApp('{% url "rmwa" appid=webapp.id %}')">
                                                Delete
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <!-- /.box-body -->
                </div>
            </div>
        </section>
    </div>


    <div class="modal modal-danger fade" id="confirmdelete" style="display: none;">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span></button>
                    <h4 class="modal-title">Deleting Web App Permenantly</h4>
                </div>
                <div class="modal-body">
                    Are you sure delete app?
                    <br>
                    Maybe you may want to press cancel to backup first...
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-outline" data-dismiss="modal" id="deletewebappconfirm" >Delete</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
{% endblock %}
{% block EXTRA_CSS %}{% endblock %}
{% block EXTRA_SCRIPT %}
    <!--suppress JSUnusedLocalSymbols -->
    <script type="text/javascript">
        function deleteWebApp(redurl){
            console.log(redurl);
            $('#confirmdelete').modal(
                {
                    backdrop: 'static',
                    keyboard: false
                }
            ).on('click', '#deletewebappconfirm', function(e){
                console.log(redurl);

                window.location.href = redurl;
            });
        }

    </script>
{% endblock %}